export const SET_AUTH = "SET_AUTH";
export const SET_UNAUTH = "SET_UNAUTH";
export const SET_USER = "SET_USER";
export const SET_LOADING_USER = "SET_LOADING_USER";
export const SET_ERROR_USER = "SET_ERROR_USER";
export const UNSET_ERROR_USER = "UNSET_ERROR_USER";

export const SET_FLASH_MESSAGE = "SET_FLASH_MESSAGE";
export const UNSET_FLASH_MESSAGE = "UNSET_FLASH_MESSAGE";

export const SET_KATEGORI = "SET_KATEGORI";
export const SET_ALL_KATEGORI = "SET_ALL_KATEGORI";
export const SET_LOADING_KATEGORI = "SET_LOADING_KATEGORI";

export const SET_KEGIATAN = "SET_KEGIATAN";
export const SET_STATUS_KEGIATAN = "SET_STATUS_KEGIATAN";
export const SET_UPDATE_KEGIATAN = "SET_UPDATE_KEGIATAN";
export const SET_ALL_KEGIATAN = "SET_ALL_KEGIATAN";
export const SET_LOADING_KEGIATAN = "SET_LOADING_KEGIATAN";
export const SET_ERROR_KEGIATAN = "SET_ERROR_KEGIATAN";
